apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata: 
  name: backend-configmap-reader
  namespace: task-platform

rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-configmap-reader-binding
  namespace: task-platform

subjects:
  - kind: ServiceAccount
    name: backend-sa
    namespace: task-platform

roleRef:
  kind: Role
  name: backend-configmap-reader
  apiGroup: rbac.authorization.k8s.io
