apiVersion: v1
kind: Pod
metadata:
  name: quota-request-success
  namespace: task-platform
spec:
  containers:
    - name: nginx
      image: nginx:latest
      resources:
        requests:
          cpu: "1.5"
          memory: 1.5Gi
        limits:
          cpu: "3"
          memory: 3Gi